### ISSUE TITLE
项目请求数据报错

### ISSUE THREAD

**Issue by Bingoliallen** [zskingking/Jetpack-WanAndroid#13]
2021-05-14 15:06:59.177 15290-15290/com.zs.zs_jetpack W/System.err: java.net.SocketTimeoutException: failed to connect to www.wanandroid.com/47.104.74.169 (port 443) from /192.168.17.44 (port 46810) after 10000ms
2021-05-14 15:06:59.177 15290-15290/com.zs.zs_jetpack W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
2021-05-14 15:06:59.178 15290-15290/com.zs.zs_jetpack W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:129)
2021-05-14 15:06:59.178 15290-15290/com.zs.zs_jetpack W/System.err:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
2021-05-14 15:06:59.178 15290-15290/com.zs.zs_jetpack W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:391)
2021-05-14 15:06:59.178 15290-15290/com.zs.zs_jetpack W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:231)
2021-05-14 15:06:59.178 15290-15290/com.zs.zs_jetpack W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:213)
2021-05-14 15:06:59.179 15290-15290/com.zs.zs_jetpack W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2021-05-14 15:06:59.179 15290-15290/com.zs.zs_jetpack W/System.err:     at java.net.Socket.connect(Socket.java:621)
2021-05-14 15:06:59.179 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.kt:63)
2021-05-14 15:06:59.179 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
2021-05-14 15:06:59.179 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
2021-05-14 15:06:59.179 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2021-05-14 15:06:59.179 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2021-05-14 15:06:59.180 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2021-05-14 15:06:59.180 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2021-05-14 15:06:59.180 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2021-05-14 15:06:59.180 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2021-05-14 15:06:59.180 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2021-05-14 15:06:59.180 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2021-05-14 15:06:59.181 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2021-05-14 15:06:59.181 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2021-05-14 15:06:59.181 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2021-05-14 15:06:59.181 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2021-05-14 15:06:59.181 15290-15290/com.zs.zs_jetpack W/System.err:     at com.zs.base_library.http.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:75)
2021-05-14 15:06:59.181 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2021-05-14 15:06:59.182 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2021-05-14 15:06:59.182 15290-15290/com.zs.zs_jetpack W/System.err:     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
2021-05-14 15:06:59.182 15290-15290/com.zs.zs_jetpack W/System.err:     at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
2021-05-14 15:06:59.182 15290-15290/com.zs.zs_jetpack W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
2021-05-14 15:06:59.182 15290-15290/com.zs.zs_jetpack W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-05-14 15:06:59.182 15290-15290/com.zs.zs_jetpack W/System.err:     at java.lang.Thread.run(Thread.java:784)

**Comment by zskingking** [comment]
> 2021-05-14 15:06:59.177 15290-15290/com.zs.zs_jetpack W/System.err: java.net.SocketTimeoutException: failed to connect to [www.wanandroid.com/47.104.74.169](http://www.wanandroid.com/47.104.74.169) (port 443) from /192.168.17.44 (port 46810) after 10000ms
> 2021-05-14 15:06:59.177 15290-15290/com.zs.zs_jetpack W/System.err: at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
> 2021-05-14 15:06:59.178 15290-15290/com.zs.zs_jetpack W/System.err: at libcore.io.IoBridge.connect(IoBridge.java:129)
> 2021-05-14 15:06:59.178 15290-15290/com.zs.zs_jetpack W/System.err: at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
> 2021-05-14 15:06:59.178 15290-15290/com.zs.zs_jetpack W/System.err: at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:391)
> 2021-05-14 15:06:59.178 15290-15290/com.zs.zs_jetpack W/System.err: at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:231)
> 2021-05-14 15:06:59.178 15290-15290/com.zs.zs_jetpack W/System.err: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:213)
> 2021-05-14 15:06:59.179 15290-15290/com.zs.zs_jetpack W/System.err: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
> 2021-05-14 15:06:59.179 15290-15290/com.zs.zs_jetpack W/System.err: at java.net.Socket.connect(Socket.java:621)
> 2021-05-14 15:06:59.179 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.kt:63)
> 2021-05-14 15:06:59.179 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
> 2021-05-14 15:06:59.179 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
> 2021-05-14 15:06:59.179 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
> 2021-05-14 15:06:59.179 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
> 2021-05-14 15:06:59.180 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
> 2021-05-14 15:06:59.180 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
> 2021-05-14 15:06:59.180 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
> 2021-05-14 15:06:59.180 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 2021-05-14 15:06:59.180 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
> 2021-05-14 15:06:59.180 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 2021-05-14 15:06:59.181 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
> 2021-05-14 15:06:59.181 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 2021-05-14 15:06:59.181 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
> 2021-05-14 15:06:59.181 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 2021-05-14 15:06:59.181 15290-15290/com.zs.zs_jetpack W/System.err: at com.zs.base_library.http.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:75)
> 2021-05-14 15:06:59.181 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 2021-05-14 15:06:59.182 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
> 2021-05-14 15:06:59.182 15290-15290/com.zs.zs_jetpack W/System.err: at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
> 2021-05-14 15:06:59.182 15290-15290/com.zs.zs_jetpack W/System.err: at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
> 2021-05-14 15:06:59.182 15290-15290/com.zs.zs_jetpack W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
> 2021-05-14 15:06:59.182 15290-15290/com.zs.zs_jetpack W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 2021-05-14 15:06:59.182 15290-15290/com.zs.zs_jetpack W/System.err: at java.lang.Thread.run(Thread.java:784)

这个是链接超时了，要不换个网络试试？
